<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HMS-QA-Din" name="ChannelAutomation.Admin.Test.AdminLoginTest" tests="17" failures="2" timestamp="10 Aug 2017 09:28:16 GMT" time="1149.960" errors="0">
  <testcase name="landOnListOfGDSPage_TC_2" time="2.721" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
  <testcase name="landOnListOfGDSPage_TC_6" time="2.525" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
  <testcase name="landOnAdminHome_TC_5" time="1.837" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
  <testcase name="backToAdminHomePagel_TC_15" time="0.059" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
  <testcase name="logoutAdmin_TC_17" time="5.756" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
  <testcase name="landOnListofChannels_TC_11" time="2.802" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
  <testcase name="saveAlotments_TC_4" time="14.905" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
  <testcase name="AdminLogin_TC_1" time="152.904" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
  <testcase name="sendRatesOnChannel_TC_14" time="553.077" classname="ChannelAutomation.Admin.Test.AdminLoginTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at ChannelAutomation.Admin.VB.VerifyRatesOnChannel.verifyrates(VerifyRatesOnChannel.java:128)
	at ChannelAutomation.Admin.Test.AdminLoginTest.sendRatesOnChannel_TC_14(AdminLoginTest.java:242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- sendRatesOnChannel_TC_14 -->
  <testcase name="clickOnChannel_TC_12" time="3.123" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
  <testcase name="landOnAdminHome_TC_9" time="6.057" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
  <testcase name="landOnAdminHome_TC_16" time="8.052" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
  <testcase name="clickOnEditPackage_TC_13" time="4.215" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
  <testcase name="SendRulesonChannel_TC_8" time="370.433" classname="ChannelAutomation.Admin.Test.AdminLoginTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at ChannelAutomation.Admin.VB.ManageAllotmentsPage.sendRestrictions(ManageAllotmentsPage.java:345)
	at ChannelAutomation.Admin.Test.AdminLoginTest.SendRulesonChannel_TC_8(AdminLoginTest.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- SendRulesonChannel_TC_8 -->
  <testcase name="landOnAllotmentMatrix_TC_3" time="9.709" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
  <testcase name="landOnAllotmentMatrix_TC_7" time="6.348" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
  <testcase name="landOnListOfGDSPage_TC_10" time="5.437" classname="ChannelAutomation.Admin.Test.AdminLoginTest"/>
</testsuite> <!-- ChannelAutomation.Admin.Test.AdminLoginTest -->
